# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Jihyun Yang
email: jihyunyang@mymail.mines.edu
description: >- # this means to ignore newlines until "baseurl:"
    Posts about computational geophysics, Machine learning and optimization.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jhgeeyang.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: jhgeeyang
github:
    profile: 'https://github.com/jhgeeyang'
name: 'Jihyun Yang'

#
paginate: 5
paginate_path: '/blog/page:num' 

# Build settings
markdown: kramdown
highlighter: rouge
remote_theme: fongandrew/hydeout
#theme: jekyll-theme-hideout
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
sidebar_home_link: true
sidebar_blog_link: '/blog' 

collections:
    news:
        output: false
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
#permalink: /:categories/:title/
# add theme
