# Site settings
title: Jihyun Yang 
url: "https://jhgeeyang.github.io"
baseurl: ""
description: >
    Blog of Jihyun

# My information
email: jihyunyang@mines.edu
author: Jihyun 
profile: Jihyun
twitter_username: 
github_username: jhgeeyang
disqus_shortname: 
linkedin_username: jhyangingp

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist

permalink: /blog/:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

paginate: 10
paginator_path: "/blog"
paginate_path: "/blog/page:num/"

# Collections
collections:
    wiki:
        output: true
        permalink: /:collection/:path/

# Comment Service
disqus:
  id: jihyunyang
  shortname: jihyunyang

google_analytics:
  ua: UA-110224147-1

google_adsense:
  client: ca-pub-3675948545737694

blame: "https://github.com/jhgeeyang/jhgeeyang.github.io/blame/master/_wiki"
edit: "https://github.com/jhgeeyang/jhgeeyang.github.io/edit/master/_wiki"
issue: "https://github.com/jhgeeyang/jhgeeyang.github.io/issues/new"

timezone: "Asia/Seoul"
